### ISSUE TITLE
请问下具体怎么装啊?

### ISSUE THREAD

**Issue by 3038922** [qwqcode/qwquiver#4]
安装前端依赖似乎不行欸 我是 ubuntu20.04.
直接build里安装么?
```sh
 ⚡ root@ncrserver  /www/wwwroot/qwquiver/frontend  ➦ c807b78  yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

**Comment by qwqcode** [comment]
首先，您需要确保您的环境安装了 node 和 yarn 这样才可以编译前端界面

```sh
➜  ~ yarn -v
1.22.10
➜  ~ node -v
v15.5.0
```

其次，似乎您的 frontend 目录为空。前端作为 [submodule](https://git-scm.com/docs/git-submodule)，您可以 clone 的时候加上 flag `--recurse-submodules` 例如：`git clone --recurse-submodules https://github.com/qwqcode/qwquiver.git` 来完整保存后端和前端

如果您想省去编译步骤，也可以直接下载：https://github.com/qwquiver/qwquiver/releases

**Comment by 3038922** [comment]
先apt 装GO环境?再直接 GO执行 qwquiver ?
那数据库咋链接?
不好意思哈 不懂WEB开发,问的问题都很小白...就像弄个网页版的系统 比EXCEL统计方便
```sh
 ⚡ root@ncrserver  ~/test  ll
total 15M
-rwxr-xr-x 1 501 staff 15M Jan 14 00:28 qwquiver
 ⚡ root@ncrserver  ~/test  go build qwquiver
can't load package: package qwquiver: cannot find package "qwquiver" in any of:
        /usr/local/go/src/qwquiver (from $GOROOT)
        /root/go/src/qwquiver (from $GOPATH)
 ✘ ⚡ root@ncrserver  ~/test  go build ./qwquiver
can't load package: package ./qwquiver: cannot find package "." in:
        /root/test/qwquiver
 ✘ ⚡ root@ncrserver  ~/test  go run ./qwquiver
package ./qwquiver: cannot find package "." in:
        /root/test/qwquiver
 ✘ ⚡ root@ncrserver  ~/test  yarn -v
ERROR: There are no scenarios; must have at least one.
 ✘ ⚡ root@ncrserver  ~/test  yarn --version
0.32+git
 ⚡ root@ncrserver  ~/test 
 ⚡ root@ncrserver  ~/test   qwquiver serve
zsh: command not found: qwquiver
 ✘ ⚡ root@ncrserver  ~/test  ./qwquiver serve
zsh: no such file or directory: ./qwquiver
 ✘ ⚡ root@ncrserver  ~/test  ll
total 15M
-rwxr-xr-x 1 501 staff 15M Jan 14 00:28 qwquiver
```

**Comment by qwqcode** [comment]
如果是Linux系统，直接下载已编译二进制文件：https://github.com/qwquiver/qwquiver/releases

命令行敲入 ./qwquiver 运行即可看到说明文档

无需 apt install golang 无需自行编译前后端

另外，不好意思 😂 其实这个系统当前正处于开发初期，由于高三时间有限，图形化配置还没来得及制作，很多操作都需要在命令行下完成，比较繁琐。

**Comment by 3038922** [comment]
> 如果是Linux系统，直接下载已编译二进制文件：https://github.com/qwquiver/qwquiver/releases
> 
> 命令行敲入 ./qwquiver 运行即可看到说明文档
> 
> 无需 apt install golang 无需自行编译前后端
> 
> 另外，不好意思 😂 其实这个系统当前正处于开发初期，由于高三时间有限，图形化配置还没来得及制作，很多操作都需要在命令行下完成，比较繁琐。

直接执不行的.
我现在编译安装了 我也趁寒假学学怎么做WEB开发好了.
ubuntu 20.04下似乎不怎么好装 
明天再研究咯 谢谢哈

**Comment by qwqcode** [comment]
> > 如果是Linux系统，直接下载已编译二进制文件：https://github.com/qwquiver/qwquiver/releases
> > 命令行敲入 ./qwquiver 运行即可看到说明文档
> > 无需 apt install golang 无需自行编译前后端
> > 另外，不好意思 😂 其实这个系统当前正处于开发初期，由于高三时间有限，图形化配置还没来得及制作，很多操作都需要在命令行下完成，比较繁琐。
> 
> 直接执不行的.
> 我现在编译安装了 我也趁寒假学学怎么做WEB开发好了.
> ubuntu 20.04下似乎不怎么好装
> 明天再研究咯 谢谢哈

不会吧，我刚刚编译的 linux 版本，并且在 ubuntu-lts 环境下测试过没问题的

确定您下载的是 https://github.com/qwquiver/qwquiver/releases/download/0.0.1/qwquiver-linux-x64.tar.gz 解压并执行 ./qwquiver ？

你那边执行提示了什么？报错吗
